# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-04-29 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('price', models.CharField(max_length=32)),
                ('author', models.CharField(max_length=32)),
                ('publisher', models.CharField(max_length=32)),
            ],
        ),
    ]
